### ISSUE TITLE
should rename ttyMFD2 to ttyGS2?

### ISSUE THREAD

**Issue by xlla** [edison-fw/meta-intel-edison#103]
when I do migrate arduino lib, I saw this statement
<pre>
system("systemctl stop serial-getty@ttyMFD2.service");
</pre>

and on Edison, I am not found that service, should it be rename?
and in meta-intel-edison/meta-intel-edison-distro/recipes-core/post-install/files/post-install.service, reference that service too.

**Comment by htot** [comment]
No, to ttyS2. That is the tty attached to console.

As you can see in mraa we already have [a patch](https://github.com/eclipse/mraa/commit/6a1ed23246e60ec8ffce1eb9f1fe595c793ca8c9) there too, so good catch for this one.

**Comment by xlla** [comment]
ok, ttySn is fine.
