### ISSUE TITLE
tri_state_all line always show 0 with gpioget

### ISSUE THREAD

**Issue by xlla** [edison-fw/meta-intel-edison#109]
I first report this issue at [here](https://github.com/edison-fw/meta-intel-edison/issues/73), in backward 6th.

I observed it is always return 0 not just after reboot.
even after explicit pull up.
<pre>
root@edison:~# gpioset gpiochip2 14=1
root@edison:~# gpioget `gpiofind TRI_STATE_ALL`
0

</pre>

I have an oled screen connected on spi bus, it works fine, after I do a gpioget on TRI_STATE_ALL line, it goes off, need reload acpi ssdt to wake up it.

**Comment by andy-shev** [comment]
When you get a value, it means that library requests that pin to be input, and driver reads input register state. According to the Edison/Arduino schematic there is a pull down R35 10kOhm which makes it always to be read as '0'. I think you are talking about explicit **built-in** pull up, which is quite weak (50kOhm or so), you can easily see that you will get a level as 1:6 of the input voltage which is not recognized as '1'.
