### ISSUE TITLE
mraa iio init wants "events"

### ISSUE THREAD

**Issue by xlla** [edison-fw/meta-intel-edison#110]
for mraa_iio_init, it is want to open folder
<pre>
/sys/bus/iio/devices/iio\:device1/events
</pre>
but in our system, there is only
<pre>
/sys/bus/iio/devices/iio\:device1/uevent
</pre>

is it deprecated?

**Comment by andy-shev** [comment]
Nope, AFAICS, https://elixir.bootlin.com/linux/v5.7-rc6/source/Documentation/ABI/testing/sysfs-bus-iio#L603

I think MRAA developers simple doesn't know how to program middle layer libraries.

That folder according to the above ABI exists only for some amount of sensors / drivers. It's optional and IIO drivers aren't obliged to implement it.
