### ISSUE TITLE
BTRFS rebooted crash

### ISSUE THREAD

**Issue by shawnhsoia97** [edison-fw/meta-intel-edison#124]
I update to latest zeus version.
I have happened to the strange status
When I did input command reboot, the system have crashed that is stop, this like below:
![image](https://user-images.githubusercontent.com/53549747/109123573-f71a0c80-7784-11eb-89d6-f61663262941.png)

But I replug power of the Edison, this system boot normally
![image](https://user-images.githubusercontent.com/53549747/109124468-e9b15200-7785-11eb-9692-dbc417afe546.png)

**Comment by htot** [comment]
It seems not a crash, but waiting (or looping) inside U-Boot. I'm a little confused, your booting a btrfs image, but U-boot says Target: blank and I believe now I have Target: btrfs. Who did you install?

BTW: I am currently on the dunfell branch as this has the diff with zeus here: https://github.com/edison-fw/meta-intel-edison/compare/zeus...htot:dunfell

**Comment by shawnhsoia97** [comment]
Sorry this is my HW issue.
I am sorry if this has caused you any misunderstand.

Thank for your quick reply.
