### ISSUE TITLE
requirement for sudo to use flashall.sh

### ISSUE THREAD

**Issue by humanoid2050** [edison-fw/meta-intel-edison#132]
The documentation states in a few places that root permissions via sudo are required for flashall.sh on Ubuntu.

Creating the file `/etc/udev/rules.d/46-edison-dfu.rules` with the following line
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0a99", MODE="0664", GROUP="plugdev"
```
will allow a user (who is a member of the plugdev group) to use the script without sudo.

**Comment by htot** [comment]
That  would be useful to add to the documentation. Would you create a patch to document how to do that and correct current refs to sudo?

**Comment by humanoid2050** [comment]
My Markdown-fu is weak, but I will certainly take a crack at it. I think Setting Up > Prerequisites for building is probably the right place to document the fix, and then add references back to that in the building and installing pages that actually use the script. Let me know if you have a better idea for the layout.

**Comment by humanoid2050** [comment]
PR #133 has changes for this.

**Comment by htot** [comment]
This will appear in gatesgarth soon to be released, thanks.
