### ISSUE TITLE
Intel Edison can't boot new flashed image

### ISSUE THREAD

**Issue by macvenez** [edison-fw/meta-intel-edison#139]
Hi,
I tried to flash the gatesgarth image provided here but the Edison won't finish the flashing procedure.
I used raspberry with flashall.sh but the process stops here...
![Immagine 2022-02-08 114840](https://user-images.githubusercontent.com/25615042/152972436-27e765a2-b2e3-4a25-b96d-8d47ef10517c.png)
that's the serial console of the Edison...any help to fix the problem?

**Comment by htot** [comment]
Interesting, I never thought to use Raspberry for this. Looking at the script I think it should be flashing edison-blankcdc (which should should work) while on windows edison-blankrndis (which I never tested). 

I am guessing you have ssh terminal open to raspberry to run flashall? What did that screen show?

Maybe you could try `./flashall --btrfs`, if that works, then it was just a bug.

But it could also be a bad usb cable.

**Comment by htot** [comment]
Thanks!
