### ISSUE TITLE
Expired gpg keys

### ISSUE THREAD

**Issue by libx264** [edison-fw/meta-intel-edison#152]
An error occurs during compilation about the impossibility of using the secret key

**Comment by htot** [comment]
The keys expired, I will send a patch to update the keys. But you can generate your own following https://edison-fw.github.io/meta-intel-edison/5.0-Creating-a-deb-repository.html#generating-you-own-gpg-key.

**Comment by lukedais** [comment]
Can extend the expiry date by running the following:

gpg --edit-key E78D3359A86650AE
key 1
expire
*desired extension*

May need to repeat this exact process for the subkey.

**Comment by htot** [comment]
This is fixed now in master / kirkstone. Thanks.
