### ISSUE TITLE
When acpi is not set clobber fails because python not found

### ISSUE THREAD

**Issue by htot** [edison-fw/meta-intel-edison#51]
https://github.com/edison-fw/meta-intel-edison/blob/a41f2a7d93e1e595ab682447639e94406cfe97a0/meta-intel-edison-distro/recipes-core/images/core-image-minimal-initramfs.bbappend#L22

Look like this needs to be either conditional on acpi or on the presence of the directory

**Comment by htot** [comment]
@alext-mkrs do you know the best way to make this conditional?

**Comment by alext-mkrs** [comment]
I think we can simply use "rm -r" here without any recipe-level
