### ISSUE TITLE
feedback: /dev/spidev5.1 seems to work fine in 5.0.0-edison-acpi-standard

### ISSUE THREAD

**Issue by ecc1** [edison-fw/meta-intel-edison#65]
Usermode access to SPI devices via /dev/spidev5.1 seems to be working fine.

**Comment by htot** [comment]
Do you think I need to correct something in the documentation? Or is there another area that's needs improvement?

**Comment by htot** [comment]
Would you care to edit the file, with how you tested as an example and send a PR? It's in markdown here: docs/_docs/Edison/Current State/4.4-hsu-i2c-spi.md

Also, I'm interested in knowing what happens with the LED while your communicating with the SPI device?

**Comment by htot** [comment]
I see. That applies only to the Edison-Ardiuno board. AFAICT the LED is muxed with a SPI line.

**Comment by xlla** [comment]
I can report here, 
I have connected an oled screen on spi driven by fbtft/fbcon.
if screen is light on, DS2 will quickly blink, about ~5hz or more.
if screen goes sleep, DS2 will off.
